"""created association between tags and articles tables

Revision ID: f031d49d3330
Revises: ae5677d67329
Create Date: 2024-07-11 21:56:52.120728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f031d49d3330'
down_revision: Union[str, None] = 'ae5677d67329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_articles',
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_articles')
    # ### end Alembic commands ###
